"""Alembic migration script template — revision id stamps go here.

Revision ID: <autogenerated>
Revises:
Create Date: <autogenerated>

This is a placeholder; Alembic will replace it with a real header when
you run ``alembic revision --autogenerate``.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = None
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
